# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11
language: swift
script:
- set -o pipefail && xcodebuild -version 
- set -o pipefail && xcodebuild -showsdks
- set -o pipefail && xcodebuild -showdestinations -workspace Example/SMToaster.xcworkspace -scheme SMToaster-Example 
- set -o pipefail && xcodebuild clean build test -enableCodeCoverage YES -workspace Example/SMToaster.xcworkspace -scheme SMToaster-Example -destination 'platform=iOS Simulator,OS=13.0,name=iPhone 8' ONLY_ACTIVE_ARCH=YES

